version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.0
    environment:
      - MARIADB_ROOT_PASSWORD=bitnami
      - MARIADB_DATABASE=filemon
    volumes:
      - 'filemon:/bitnami'
    ports:
      - 0.0.0.0:5506:3306
  phpmyadmin:
    image: docker.io/bitnami/phpmyadmin:5
    ports:
      - '8080:8080'
      - '443:8443'
    depends_on:
      - mariadb
volumes:
  filemon:
    driver: local

